name: terraform-run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  ci-terraform:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: infrastructure/terraform
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      GCP_REGION: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set GCP Access Token
        run: echo "GCP_ACCESS_TOKEN=${{ secrets.GCP_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /path/to/service-account.json # If using a service account
          GCP_ACCESS_TOKEN: ${{ secrets.GCP_ACCESS_TOKEN }} # Use directly
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          TF_LOCK_TABLE: ${{ secrets.TF_LOCK_TABLE }}
          TF_STATE_PREFIX: ${{ secrets.TF_STATE_PREFIX }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          terraform init -input=false

      - name: Terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /path/to/service-account.json # If using
          GCP_ACCESS_TOKEN: ${{ secrets.GCP_ACCESS_TOKEN }} # Use directly
          TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform plan -out=tfplan -input=false

      - name: Terraform apply (auto-approve on main)
        if: github.ref == 'refs/heads/main' && success()
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve tfplan
